resources:
  repositories:
    - repository: cli11
      type: github
      endpoint: gh
      name: cliutils/cli11
      ref: refs/tags/v2.2.0

variables:
- group: NuGet

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    displayName: "Cloning build-nuget-cli11"
  - checkout: cli11
    displayName: "Cloning cli11"

  - powershell: 'ls'
    displayName: "Check directories"

  - task: CMake@1
    displayName: "Making CLI11"
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      cmakeArgs: '-DCMAKE_INSTALL_PREFIX="./build-nuget-cli11/" -DCLI11_INSTALL=ON -DCLI11_SINGLE_FILE=ON -DCLI11_BUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -B "./BUILD" ./cli11' 
      
  - task: CMake@1
    displayName: "Building CLI11"
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      cmakeArgs: '--build "./BUILD"'

  - task: CMake@1
    displayName: "Installing CLI11"
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      cmakeArgs: '--install "./BUILD"'
    
  - task: NuGetCommand@2
    displayName: "Packaging NuGet Pkg"
    inputs:
      command: 'pack'
      packagesToPack: './build-nuget-cli11/cli11.nuspec'
      packDestination: '$(System.DefaultWorkingDirectory)'
      versioningScheme: 'off'
      
  - script: nuget push ./build-nuget-cli11/*.nupkg -src https://api.nuget.org/v3/index.json -ApiKey $(nuget-apikey)
    displayName: "Pushing NuGet Pkg"