resources:
  repositories:
    - repository: cli11
      type: github
      endpoint: gh
      name: cliutils/cli11
      ref: refs/tags/v2.2.0

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    displayName: "Cloning build-nuget-cli11"
  - checkout: cli11
    displayName: "Cloning cli11"

  - powershell: 'ls'
    displayName: "Check directories"

  - task: CMake@1
    displayName: "Making CLI11"
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      cmakeArgs: '-DCMAKE_INSTALL_PREFIX="./INSTALL" -DCLI11_INSTALL=ON -DCLI11_SINGLE_FILE=ON -DCLI11_BUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -B "./BUILD" ./cli11' 
      
  - task: CMake@1
    displayName: "Building CLI11"
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      cmakeArgs: '--build "./BUILD"'

  - task: CMake@1
    displayName: "Installing CLI11"
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      cmakeArgs: '--install "./build-nuget-cli11"'
    
  - task: NuGetCommand@2
    displayName: "Packaging NuGet Pkg"
    inputs:
      command: 'pack'
      packagesToPack: './build-nuget-cli11/cli11.nuspec'
      packDestination: '$(System.DefaultWorkingDirectory)'
      versioningScheme: 'off'

  - task: NuGetAuthenticate@0
    inputs:
      nuGetServiceConnections: nuget
      
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(System.DefaultWorkingDirectory)/build-nuget-cli11/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'nuget'