resources:
  repositories:
    - repository: cli11
      type: github
      endpoint: gh
      name: cliutils/cli11
      ref: refs/tags/v2.2.0

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials : true
  - checkout: cli11
    persistCredentials : true

  - task: CMake@1
    displayName: "Making CLI11"
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      cmakeArgs: '-DCMAKE_INSTALL_PREFIX="./INSTALL" -DCLI11_INSTALL=ON -DCLI11_SINGLE_FILE=ON -B "BUILD"'
      
  - task: CMake@1
    displayName: "Building CLI11"
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      cmakeArgs: '--build ./BUILD'

  - task: CMake@1
    displayName: "Installing CLI11"
    inputs:
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      cmakeArgs: '--installl ./BUILD'